### ISSUE TITLE
Screen capture lib

### ISSUE THREAD

**Issue by smasherprog** [namkazt/NKStreamer-Server-#1]
namkazt,

If you are not using the onFrameChanged callback, you shouldn't define it. Even an empty function definition causes extra work to occur.
Additionally, if you want to be more efficient sending data to clients, you can use the onFrameChanged to send only the changes to connected clients.  
onFrameChanged  is called when there is a change in the screen and it only contains the changes.

Starting the library will call onFrameChanged for each monitor and it will be the entire screen, then after that will be diffs.

**Comment by smasherprog** [comment]
Also, if you dont want the mouse image, dont define that callback either. If you define the callback, the library assumes you want the image and does work.

**Comment by namkazt** [comment]
@smasherprog thank you for that. :D I did'nt know that.
